name: Fetch and Upload Data to PythonAnywhere

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour
  workflow_dispatch:     # Allow manual triggering of the workflow

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Step 3: Install dependencies with fixed versions
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas==2.0.3 requests==2.32.3 numpy==1.23.5 setuptools==75.1.0

    # Step 4: Run the Python script
    - name: Run Script to Fetch Data and Upload
      run: python extract.py
      env:
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
