name: Fetch Data Hourly

on:
  schedule:
    - cron: "0 * * * *"  # Runs at the top of every hour
  workflow_dispatch:  # Allows manual runs from the GitHub Actions UI

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you want

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests 

    - name: Run Fetch Script
      run: python extract.py

    - name: Upload Data Artifact
      uses: actions/upload-artifact@v3
      with:
        name: fetched_data
        path: fetched_data.csv
